# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run

on:
  workflow_run:
    workflows: ["CI"]  
    types:
     - completed
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Increase job timeout to 30 minutes
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runner's shell
      - name: Start minikube
        run: |
          minikube start --driver=docker
        timeout-minutes: 20

      - name: Check Minikube Status
        run: |
          minikube status

      - name: Apply file yaml
        run: |
          kubectl apply -f configMap.yaml -f secrets.yaml -f persistentVolume.yaml -f service.yaml -f deployment.yaml

      - name: Wait for all Pods to be Running
        run: |
          for i in {1..60}; do
            if kubectl get pods --all-namespaces | grep -v Running | grep -v Completed; then
              echo "Waiting for pods to be in Running state..."
              kubectl get all
              sleep 10
            else
              echo "All pods are in Running state."
              kubectl get all
              break
            fi
          done

      - name: Check resources
        run: |
          kubectl get all
