# This is a basic workflow to help you get started with Actions

name: CI Pineline

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensure submodules are checked out with the main repository

      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Set up databases
        run: |
          docker compose -f docker-compose.yml build student-service-mysql
          docker compose -f docker-compose.yml build auth-service-mysql
          docker compose -f docker-compose.yml build mongodb  
          docker compose -f docker-compose.yml build postgresql
          
      - name: Set up databases admin tool
        run: |
          docker compose -f docker-compose.yml build auth-phpmyadmin
          docker compose -f docker-compose.yml build student-phpmyadmin
          docker compose -f docker-compose.yml build mongo-express
          docker compose -f docker-compose.yml build pgadmin
          
                              
  
      - name: Build back-end application images
        run: |
          cp class-management-auth-service/Dockerfile .
          docker compose -f docker-compose.yml build class-mangement-auth-service
          cp class-management-student-service/Dockerfile .
          docker compose -f docker-compose.yml build class-management-student-service
          cp class-management-lecturer-service/Dockerfile .
          docker compose -f docker-compose.yml build class-management-lecturer-service
          cp class-management-class-service/Dockerfile .
          docker compose -f docker-compose.yml build class-management-class-service
      
        
  
      - name: Build front-end application image
        run: |
          cp class-management-fe/Dockerfile .
          docker compose -f docker-compose.yml build class-mangement-fe
  
      - name: Push images to Docker Hub
        run: docker compose -f docker-compose.yml push
  
      - name: Clean and Deploy to Dev Environment
        run: |
          docker images
          docker compose -f docker-compose.yml down -v
          yes | docker container prune
          docker compose -f docker-compose.yml up -d
          docker compose ps
          docker network ls
          docker volume ls
  
      - name: Clean up
        run: docker logout
